import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import CharacterList from '../components/CharacterList';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css';

export default function Home({ characters }) {
  const [character, setCharacter] = useState(characters);

  const fetchCharacters = async (url) => {
    const response = await fetch(url);
    const nextCharacter = await response.json();
    setCharacter(nextCharacter);
  };

  return (
    <div>
      <Head>
        <title>R&M</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CharacterList
        characters={character}
        className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5"
      ></CharacterList>
      <button onClick={() => fetchCharacters(character.info.prev)}>
        Previous
      </button>
      <button onClick={() => fetchCharacters(character.info.next)}>Next</button>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch('https://rickandmortyapi.com/api/character/');
  console.log(response);
  const characters = await response.json();
  return {
    props: {
      characters,
    },
  };
}
