import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import CharacterList from '../components/CharacterList';
import styles from '../styles/Home.module.css';

export default function Home({ characters }) {
  const [character, setCharacter] = useState([]);
  return (
    <div className={styles.container}>
      <Head>
        <title>R&M</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CharacterList characters={characters}></CharacterList>
    </div>
  );
}

export async function getServerSideProps(context) {
  const response = await fetch('https://rickandmortyapi.com/api/character/');
  // const response = await fetch('https://pokeapi.co/api/v2/');
  console.log(response);
  const characters = await response.json();
  return {
    props: {
      characters,
    },
  };
}
