import Head from 'next/head';
import { useState } from 'react';
import CharacterList from '../components/CharacterList';
import { GetServerSideProps, NextPage } from 'next';
import { Character, GetCharacterResults } from '../types';

export default function Home({ characters }) {
  const [character, setCharacter] = useState(characters);

  const fetchCharacters = async (url: string) => {
    const response = await fetch(url);
    const nextCharacter = await response.json();
    setCharacter(nextCharacter);
  };

  return (
    <div>
      <Head>
        <title>R&M</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mb-19">
        <img
          src="/logos.png"
          alt="image"
          height="700"
          width="700"
          className="mr-auto ml-auto"
        ></img>
      </header>
      <div className="flex justify-end">
        <button
          className="bg-slate-700 hover:bg-slate-600 text-white font-semi-bold py-2 p px-4 rounded mb-3 mr-3"
          onClick={() => fetchCharacters(character.info.prev)}
        >
          Prev
        </button>
        <button
          className="bg-slate-700 hover:bg-slate-600 text-white font-semi-bold py-2 px-4 rounded mb-3"
          onClick={() => {
            fetchCharacters(character.info.next);
          }}
        >
          Next
        </button>
      </div>
      <div className="cardo">
        <CharacterList
          characters={character}
          className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5"
        ></CharacterList>
      </div>
      <div className="flex justify-end">
        <button
          className="bg-slate-700 hover:bg-slate-600 text-white font-semi-bold py-2 p px-4 rounded mb-3 mr-3 mt-3"
          onClick={() => fetchCharacters(character.info.prev)}
        >
          Prev
        </button>
        <button
          className="bg-slate-700 hover:bg-slate-600 text-white font-semi-bold py-2 px-4 rounded mb-3 mt-3 "
          onClick={() => {
            fetchCharacters(character.info.next);
          }}
        >
          Next
        </button>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch('https://rickandmortyapi.com/api/character/');
  const characters: GetCharacterResults = await response.json();
  return {
    props: {
      characters,
    },
  };
};
